CREATE TABLE IF NOT EXISTS users
(
    id         SERIAL PRIMARY KEY,
    full_name  VARCHAR NOT NULL,
    username   VARCHAR NOT NULL UNIQUE,
    password   VARCHAR NOT NULL,
    role VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);